package:
  name: poreTally
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/cvdelannoy/poreTally.git

requirements:
  build:
    - python3
    - conda
    - snakemake
    - pyYAML
    - mappy
    - biopython
    - ete3
    - tabulate
  run:
    - python3

about:
  home: https://github.com/cvdelannoy/poreTally
  license: GPL-3.0
  license_file: LICENSE